name = "moving-checklist"
compatibility_date = "2024-02-15"

[build]
command = "npm run build"
node_version = "20.0.0"

[build.environment]
NODE_VERSION = "20.0.0"

# Next.js用の設定を追加
[build.processing]
skip_missing = true

[build.processing.html]
keep_data_url = true

[build.processing.css]
bundle = true
minify = true

[build.processing.js]
bundle = true
minify = true

[build.processing.images]
compress = true 